### PR TITLE
Check for option to keep vm for courses

### PR DESCRIPTION
**Pull request by jggoebel**
These are the UI additions needed for https://github.com/hobbyfarm/gargantua/pull/89

It checks of the "Keep VM" Option is set, otherwise VMs will not be kept over the course.

### CODE REVIEW

**Comment by ebauman** [comment]
rebase for ci/cd ?

**Comment by jggoebel** [comment]
I also added a small improvement to allow users to force finish a session when the VM is shared over the course. Sometimes users break their machines which then results in problems where the best solution was to create a new account. This should fix it.

**Comment by ebauman** [comment]
waiting on https://github.com/hobbyfarm/admin-ui/pull/97#issuecomment-976972693 before merging this

**Comment by raphinesse** [comment]
I added a computed property that encapsulates the logical expression that determines if the VM should be kept running when finishing the course. I hope that's OK.

**Pull request merged**
