### PR TITLE
Fix for PR #66 - Full terminal and sidebar

### PR DESCRIPTION
**Pull request by jggoebel**
This PR resolves the merge conflicts with PR #66.

hf_full-terminal

Also the position of the signpost after the button has been improved to associate it with the button next to it.
Added functioniality for "hidden text" as mentioned in #139 

hf_hidden_closed
hf_hidden_open

The hidden text can be created in the markdown with the following syntax:

````
```hidden:Hidden Text Summary
This is the hidden Text that opens and closes after a click on the summary
```
````

### CODE REVIEW

**Comment by jggoebel** [comment]
Uses 
https://github.com/hobbyfarm/gargantua/pull/52

**Comment by ebauman** [comment]
See hobbyfarm/gargantua#81 now.

**Comment by ebauman** [comment]
Couple things. 

* When resizing the shell, the resize strings get written to the terminal. Would be nice if they didn't show in the user's terminal. Example:
Screen Shot 2021-07-20 at 1 02 14 PM


* I would like more space on the top, bottom, and right of the terminal. Currently the terminal extends out to the browser window's edge. Can we add a margin there? Something vmware clarity compat, like 24px or whatever their baseline is. I manually adjusted this in the browser to yield this, which looks a lot cleaner:
Screen Shot 2021-07-20 at 1 01 31 PM

* I would like the same space treatment given to the step sidebar. It's fine if the step sidebar and the terminals are only a few pixels away from each other, but I don't want the content slammed up to the edges of the browser - I'm not a fan of the look & feel there. 

* Can we widen the step display a bit? Or make it adjustable for the user (might be out of scope for this PR). It's a bit slim in this redesign compared to `master` (or maybe that's just my impression). 

Otherwise, this is great, and works really well with the changes in hobbyfarm/gargantua#81.

**Comment by jggoebel** [comment]
I am using Firefox on Windows and can not experience that the resize strings are written to the terminal, but i will look into this.

We were planning onto adding a adjustable slider for the markdown and the terminal. But this may take a while.

The margins will be added in the next days.

**Comment by ebauman** [comment]
This was Firefox on OSX (Catalina, FF 89.0.2). 

Yeah, that slider is not going to be simple to implement. Could you statically widen this a little bit and save the slider for a separate body of work?

**Comment by jggoebel** [comment]
Okey i will look into this on Firefox on OSX,

Yes, it already was my intention to widen it a bit and implement the slider in the future.

**Comment by ebauman** [comment]
Awesome, thanks @jggoebel

**Comment by jggoebel** [comment]
I already added the margins: margins

**Comment by PhilipAB** [comment]
> Couple things.
> 
> * When resizing the shell, the resize strings get written to the terminal. Would be nice if they didn't show in the user's terminal. Example:
>   Screen Shot 2021-07-20 at 1 02 14 PM

@ebauman have you tested the UI alongside the gargantua implementation ([hobbyfarm/gargantua#81](https://github.com/hobbyfarm/gargantua/pull/81))?

We were able to reproduce the described behaviour without the new gargantua impl. However, using it we should catch and handle resize events, not writing them to our terminal:
https://github.com/hobbyfarm/gargantua/pull/81/commits/1d0915d2d3f4a6484ab38825cb152103a2dd9c2e#diff-32aa1c757195281541a8da10de47d543bfb580365836bbfc3baae79244d0c9bcR30-R39

**Comment by ebauman** [comment]
I will try again. I thought I had checked out that PR and ran it, but perhaps I didn't.

**Comment by ebauman** [comment]
@PhilipAB I tested this against hobbyfarm/gargantua#81 and was able to recreate on both Firefox and Chrome (both latest, running on OS X 10.15.7.

**Comment by ebauman** [comment]
I figure out the testing issue. I had been inadvertently pointing my shell sessions at a different instance, that was using old code. Fixed that, and this works very well.

**Comment by ebauman** [comment]
@jggoebel can you fix merge conflict? take your changes please.

**Comment by jggoebel** [comment]
@ebauman i fixed the conflicts.

**Comment by jggoebel** [comment]
What is the current status on this?

**Comment by ebauman** [comment]
@jggoebel MERGED is the current status :)

**Comment by jggoebel** [comment]
Small addition:
@PhilipAB pointed out that nested code blocks also work with the hidden block element implemented in this PR.

 ````
 ```hidden:Hidden Text Summary
 This is the hidden Text that opens and closes after a click on the summary
~~~ctr:node01
echo "this gets executed on node01"
~~~
```
 ````

**Pull request merged**
