### PR TITLE
v0.3.0 - New UI theme and bugfixes

### LINKED ISSUE #7: Look into sleeping/restoring the SSH and/or websocket connections
Would it be a decent idea to sleep a terminal session after a period of inactivity? The user could click to restore the connection, etc.

### LINKED ISSUE #28: Finish Button Anywhere
Finish Button should be next to Pause Button as well as on the last step

### LINKED ISSUE #33: keepalive continues to run even after you "finish" the scenario session
Found in ui 0.2.0

### PR DESCRIPTION
**Pull request by ebauman**
- New theme! Reskinned to brighten up buttons, change typography, etc. 
- Prevent running of keepalive loop after scenario completion (fixes #33)
- Put finish button in header of step page (fixes #28)
- Added restore logic for websocket connections (kinda fixes #7)
- Added additional status to VM claim page for when machines are being dynamically provisioned

### CODE REVIEW

**Comment by ebauman** [comment]
@Oats87 @hall I would love your input and thoughts on this.

**Comment by hall** [comment]
I get an error when trying to login using `hobbyfarm/ui:0.3.0`:
```
ERROR TypeError: "e.error is undefined"
```
That's printed to the console when I click "login" and no network calls are triggered. I can do some more debugging next week but that's my initial finding.

**Comment by hall** [comment]
I only get that error when using the Helm chart; with `docker run` it works as usual :+1:
```
docker run --env HF_SERVER=<gargantua-endpoint> -p 8080:80 hobbyfarm/ui:0.3.0
```

**Comment by ebauman** [comment]
Thanks @hall much appreciated

**Pull request merged**
