### PR TITLE
add insecure flag

### PR DESCRIPTION
**Pull request by hall**
This adds an `--insecure` flag that will prepend `http://` (and `ws://`) to the backend endpoints. For parity, these changes also prepend the secure versions (`https://` and `wss://`) by default.

### CODE REVIEW

**Comment by hall** [comment]
This solves issue #34.

**Comment by ebauman** [comment]
Would it be a good decision to separate out insecure options for the API server, and the shell server separately? e.g. --insecure-api --insecure-shell. Or would that be a) too much work and b) potentially cause issues in the browser with mixed-security loading?
I don't lean one way or another, curious on your thoughts @hall

**Comment by hall** [comment]
I don't think it would be too much work; the only concern I have is if there's a good use-case. We could do something like `--insecure` that accepts a comma-delimited list of which specific endpoints to toggle (where an empty list means "all").

It should only cause mixed content problems if the frontend is served over `https` and one of the backends are not (which isn't what I'm trying to do but maybe someone else is :man_shrugging:).

**Comment by ebauman** [comment]
Tell you what - let's leave it as is for now, and if someone has a compelling case for turning off one but not the other, we can revisit.

**Pull request merged**
